# server
server:
  port: 9090
  context-path: /meedesidy


# 日志
logging:
  file: /tmp/logs/log.log
  level:
    org:
      springframework:
        web: INFO
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/       