# server
server:
  port: 9090
  context-path: /

# 日志
logging:
  file: /tmp/logs/log.log
  level:
    org:
      springframework:
        web: DEBUG
        dao: DEBUG

# thymeleaf
spring:
  aop:
    auto: true
  thymeleaf:
    DEFAULT_PREFIX: classpath:/templates/
    DEFAULT_SUFFIX: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jeedey?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
  jpa: 
    show-sql: true
  spring:
    messages:
      basename: message
      encoding: UTF-8
    
mybatis: 
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: tk.mapper.model
  mvc:
    view:
      prefix: /
      suffix: .html

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
